[package]
name = "learn_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
rand = "0.8.0"
num = "0.4"
itertools = "0.10.1"
